import 'package:flutter/material.dart';

final MaterialColor primaryColor = Colors.blueGrey;
final MaterialAccentColor secondaryColor = Colors.deepOrangeAccent;

const int NUMBER_OF_ROUNDS = 7;
const int MIN_PLAYERS = 3;
const String APP_TITLE = 'Cards Against Agility';

final List<String> blackCards = <String>[
  'If there was a horror movie about this sprint, __ would be the ugly villain.',
  'Who needs deadly weapons when we have __',
  '__ is awesome in theory, but a mess in practice',
  'Without __ our sprint would have been worse than the coffee in the office.',
  'If it were up to me, __ would die and stay dead',
  'If I have to hear about __ one more time, I will rage quit',
  'In \'Sprint Hell\' sinners are subjected to __ for all eternity',
  'If this sprint was a video game, __ would have been the big boss fight',
  'The reason why I drink is __',
  'I still haven\'t forgotten about __',
  'In the last sprint, __ was less terrible than usual',
  'If I could improve two things, it would be __ and those awful Star Trek films',
  'If there was a zombie apocalypse, I would happily destroy the brains of __',
  'If the devil turned up to our stand-up, he would say __ !',
  'If I could be another Dev for a day, I would focus on __',
  'Sometimes I can\'t sleep because of __',
  'Let\'s do __ they said, it will be fun, they said',
  'My therapist is giving me great advice to deal with __',
  'This sprint, we levelled up our __ skills',
  'Please write __ on my tombstone',
  'If I could teach everyone one thing, it would be __',
  'In \'Sprint Heaven\' good devs get all the __ they want',
  'I got 99 problems, but __ ain\'t one',
  'If I had only an hour left to live, I would __',
  'Make __ great again!',
  'The best things about our team is __',
  'According to me, our biggest success lately is __',
  'The best part of our product is __',
];

final List<String> whiteCards = <String>[
  'Githooks',
  'Task ownership',
  'Branches',
  'Pull requests',
  'Story Points',
  'A billion Story Points!',
  'The Matrix',
  'Agile',
  'Prioritization',
  'Scrum',
  'User Stories',
  'Feature Planning',
  'Refinement',
  'Project Boards',
  'Bugs',
  'Product Vision',
  'Frontend',
  'Stakeholders',
  'Jira',
  'Sub-tasks',
  'Test Automation',
  'Code Quality',
  'Javascript',
  'HTML',
  'Backend',
  'Stand-ups',
  'Product Demos',
  'Finish everything in the Sprint',
  'Think before Coding',
  'Lack of Specs',
  'Lack of Planning',
  'Continuous Improvement',
  'Scrum Masters',
  'Product Owners',
  'Releases',
  'Burndown',
  'Code Freeze',
  'QA',
  'Specifications',
  'Hotfixes',
  'Our Definition of Done',
  'Refactoring',
  'Merging',
  'API',
  'Deployment',
  'Video calls',
  'UX',
  'Tech debt',
  'Point estimation',
];

final List<String> colors = <String>[
  'Red',
  'Green',
  'Yellow',
  'Blue',
  'Pink',
  'Orange',
  'Purple',
  'Brown',
  'White',
  'Black',
  'Grey',
];

final List<String> animals = <String>[
  'Cat',
  'Dog',
  'Cow',
  'Monkey',
  'Horse',
  'Bird',
  'Fish',
  'Bear',
  'Turtle',
  'Panda',
  'Elephant',
  'Wolf',
  'Penguin',
  'Kangaroo',
  'Giraffe'
];
